server:
  port: 8088
spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/dbName?characterEncoding=UTF-8&useSSL=true
#    username: mysqlUsername
#    password: mysqlPassword
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: ncdb
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: jiangnan.edu.model